### ISSUE TITLE
Backpack Item is steve head

### ISSUE THREAD

**Issue by DanDeMedicMan** [GeorgH93/Minepacks#95]
Says what it is on the tin

**Comment by GeorgH93** [comment]
Whats the output of `/backpack version`? Whats your config? What's your client version?

**Comment by DanDeMedicMan** [comment]
2.3.9 Release
Spigot 1.16.1

**Comment by MrLadMan** [comment]
I have the same release and spigot version as DanDeMedicMan, with the same issue.

**Comment by GeorgH93** [comment]
Fixed with [this update](https://www.spigotmc.org/resources/minepacks-backpack-plugin-mc-1-7-1-16.19286/update?update=343651).

**Comment by maximsGitHub** [comment]
I still have the same problem with update 2.3.10

Running on 1.16.6 Paper

**Comment by GeorgH93** [comment]
Are you sure that the item has not been added by the v2.3.9 version? v2.3.10 will not fix existing backpack items (they should get fixed once a player losses their inventory (death, /clearinventory, ...)).
